name: .NET build Linux deb publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install Deb tool
      run: dotnet tool install --global dotnet-deb
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish Linux Deb package
      run: dotnet publish /t:CreateDeb /p:TargetFramework=net5.0 /p:RuntimeIdentifier=linux-x64 /p:Configuration=Release /p:PublishSingleFile= --self-contained true
    - name: Upload Linux-64 Deb Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TWatchDesigner-Linux64-Deb
        path: /home/runner/work/Playground/Playground/src/TWatchSKDesigner/bin/Release/net5.0/linux-x64/TWatchSKDesigner.1.0.0.linux-x64.deb
